language: python
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r base_requirements.txt
  - pip install -U pytest pytest-cov coveralls flake8 isort
  - pip install -e .
script:
  - python -m pytest --cov .
  - flake8
  - isort --check-only --recursive ./kubepy/ ./tests/
after_success:
  - coveralls
