version: 2.1

workflows:
  test:
    jobs:
      - test_3-7
      - test_3-8
      - test_3-9
      - test_3-10
      - test_3-11

template: &template
  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install -r base_requirements.txt
          pip install -U pytest pytest-cov coveralls flake8 flake8-commas isort
          pip install -e .
    - run:
        name: run tests
        command: python -m pytest --cov .
    - run:
        name: run static analysis
        command: |
          flake8
          isort --check-only --recursive ./kubepy/ ./tests/

jobs:
  test_3-7:
    docker:
      - image: cimg/python:3.7
    <<: *template
  test_3-8:
    docker:
      - image: cimg/python:3.8
    <<: *template
  test_3-9:
    docker:
      - image: cimg/python:3.9
    <<: *template
  test_3-10:
    docker:
      - image: cimg/python:3.10
    <<: *template
  test_3-11:
    docker:
      - image: cimg/python:3.11
    <<: *template
